"""
Django settings for dogeCoin project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
import re
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


""" Heroku environ var
environ({'PYTHONUNBUFFERED': 'true', 'DATABASE_URL': 'postgres://tzhdkcpbdyhzon:0b9686a278
8afa2c4445961a3a016901c2e352be41a4f742a74ca0da9aa07f0e@ec2-35-174-35-242.compute-1.amazonaws.com:5432/db0hn1c1j05m4l', 'PYTHONHASHSEED': 'random', 'PWD': '/app', 'PORT': '38731', 'GUNICORN_CMD_ARGS': '--access-logfile -', 'DYNO_RAM': '512', 'HOME': '/app', 'LANG': 'en_US.UTF-8', 'FORWARDED_ALLOW_IPS': '*', 'PYTHONPATH': '/app', 'DISABLE_COLLECTSTATIC': '1', 'PYTHONHOME': '/app/.heroku/python', 'LIBRARY_PATH': '/app/.heroku/vendor/lib:/app/.heroku/python/lib:', 'SHLVL': '0', 'WEB_CONCURRENCY': '3', 'LD_LIBRARY_PATH': '/app/.heroku/vendor/lib:/app/.heroku/python/lib:', 'PS1': '\\[\\033[01;34m\\]\\w\\[\\033[00m\\] \\[\\033[01;32m\\]$ \\[\\033[00m\\]', 'PATH': '/app/.heroku/python/bin:/usr/local/bin:/usr/bin:/bin', 'DYNO': 'web.1', '_': '/app/.heroku/python/bin/gunicorn', 'SERVER_SOFTWARE': 'gunicorn/20.1.0', 'DJANGO_SETTINGS_MODULE': 'dogeCoin.settings'})
# a = 'postgres://tzhdkcpbdyhzon:0b9686a2788afa2c4445961a3a016901c2e352be41a4f742a74ca0da9aa07f0e@ec2-35-174-35-242.compute-1.amazonaws.com:5432/db0hn1c1j05m4l'
"""
NAME = 'powerornahh'
USER = 'powerornahh'
PASS = 'mostdope'
HOST = '127.0.0.1'
PORT = '5432'

if(os.environ['PWD'].find("app") >= 0):
    db_url_pattern = """
        postgres://(?P<user>\w*):(?P<pass>\w*)@(?P<host>[\w\-\.]*):(?P<port>\d*)\/(?P<name>\w*)
    """
    m = re.search(re.compile(db_url_pattern, re.MULTILINE | re.VERBOSE),
                os.environ['DATABASE_URL'])

    NAME = m.group('name')
    USER = m.group('user')
    PASS = m.group('pass')
    HOST = m.group('host')
    PORT = m.group('port')



# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4x6tc!%kz!@0u(c3^v8#9v9=v(y4nbqnmz4cu0ml*suw91$&9k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["localhost", "0.0.0.0", "127.0.0.1", "dogec01n.herokuapp.com"]


# Application definition

INSTALLED_APPS = [
    'home',
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dogeCoin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dogeCoin.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
       'ENGINE': 'django.db.backends.postgresql',
        'NAME': NAME,
        'USER': USER,
        'PASSWORD': PASS,
        'HOST': HOST,
        'PORT': PORT,
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
